input_bag: "/media/prabuddhi/Crucial X9/Human_sensing_bags/Day3/1"
segments:
  - output_bag: "/media/prabuddhi/Crucial X9/Human_sensing_bags/Splits/bag1"
    start_time: 10
    end_time: 15
  - output_bag: "/media/prabuddhi/Crucial X9/Human_sensing_bags/Splits/bag2"
    start_time: 18
    end_time: 30
  - output_bag: "/media/prabuddhi/Crucial X9/Human_sensing_bags/Splits/bag3"
    start_time: 45
    end_time: 60

